### ISSUE TITLE
4.0 TODO

### ISSUE THREAD

**Issue by spennythug** [unl/UNL_MediaHub#192]
UI TODOs:

- [x] **Edit Channel Deatils**(started)
- [x] Remove Delivery Options
- [x] **Do all the edit media stuff**
- [x] Remove channels from edit media
- [x] Set image progress styles
- [x] Tool tips (again) 
- [x] Match tool tips with to labels.  
- [x] Remove copy inputs from channel edit page and add rss link to channel page.

- [x] Frontpage icons
- [x] Featured Icon text. Frontpage
- [x] Search bars are a little ugly
- [x] Move search down a little. Channels and browse.
- [x] Consider Visited/Unvisited link color for teasers
- [x] First Browse Media Teaser styling. Get feedback from Ryan
- [x] New default channel images
- [x] Alphabetical sort for channels
- [x] Line wrap for stats
- [x] Add Tag is pretty ugly
- [x] Sign on to add tags. Make pretty
- [ ] Strip old/unused styles
- [x] Use correct tool tip
- [x] Make description a tool tip
- [x] Disabled publish styles
- [x] Style your channels
- [x] Style legends 
- [x] Remove "your videos" and "your audio"
- [x] Style uploading text
- [x] Progress Bar?
- [x] Add edit/delete links to channel/media teasers
- [x] Move tags underneath basic information. include description that they are also itunes keywords
- [x] Channel image not required 
- [x] Extra Save button
- [x] Does not stay considered
- [x] removed related channel play button from view media view.
- [x] if can edit tags
- [x] replace all rocketships 
- [x] Thumbnails (edit / audio and video)
- [x] Recent videoS
- [x] share button on videos 
- [ ] Email, lnkedin, twitter, facebook, goURL
- [x] Explore AudioVis
- [x] Empty tags remove placeholder or somethin'

Programming TODOs:
- [ ] Manager Breadcrumbs 
- [x] Fix Share link
- [x] Embed link
- [x] Look into tags (Search Results)
- [x] Return from single sign on to correct page (For add tags/comments)
- [ ] Strip old JS
- [x] Remove channel subscriptions (removed from UI)
- [x] Remove "Manage your channel"
- [x] **Move URLs/edit channel users to edit channel details**
- [x] **why did Spencer's video upload as audio!?**
- [x] Check that edit media page validation is working
- [x] Check that edit media form is submitting
- [x] Make sure the media in water channel can have the water flow fields 
- [x] work on edit channel users so Spencer can edit
- [x] Fix delete Form
- [x] Add a delete link to the edit media page
- [x] Must have: only people who can edit video details can add/remove tags - https://github.com/unl/UNL_MediaHub/issues/132
